from pysotopelib import CStoZ

def test_ZtoCS():
    assert CStoZ.ChemSymtoZ("H") == 1
    assert CStoZ.ChemSymtoZ("He") == 2
    assert CStoZ.ChemSymtoZ("Li") == 3
    assert CStoZ.ChemSymtoZ("Be") == 4
    assert CStoZ.ChemSymtoZ("B") == 5
    assert CStoZ.ChemSymtoZ("C") == 6
    assert CStoZ.ChemSymtoZ("N") == 7
    assert CStoZ.ChemSymtoZ("O") == 8
    assert CStoZ.ChemSymtoZ("F") == 9
    assert CStoZ.ChemSymtoZ("Ne") == 10
    assert CStoZ.ChemSymtoZ("Na") == 11
    assert CStoZ.ChemSymtoZ("Mg") == 12
    assert CStoZ.ChemSymtoZ("Al") == 13
    assert CStoZ.ChemSymtoZ("Si") == 14
    assert CStoZ.ChemSymtoZ("P") == 15
    assert CStoZ.ChemSymtoZ("S") == 16
    assert CStoZ.ChemSymtoZ("Cl") == 17
    assert CStoZ.ChemSymtoZ("Ar") == 18
    assert CStoZ.ChemSymtoZ("K") == 19
    assert CStoZ.ChemSymtoZ("Ca") == 20
    assert CStoZ.ChemSymtoZ("Sc") == 21
    assert CStoZ.ChemSymtoZ("Ti") == 22
    assert CStoZ.ChemSymtoZ("V") == 23
    assert CStoZ.ChemSymtoZ("Cr") == 24
    assert CStoZ.ChemSymtoZ("Mn") == 25
    assert CStoZ.ChemSymtoZ("Fe") == 26
    assert CStoZ.ChemSymtoZ("Co") == 27
    assert CStoZ.ChemSymtoZ("Ni") == 28
    assert CStoZ.ChemSymtoZ("Cu") == 29
    assert CStoZ.ChemSymtoZ("Zn") == 30
    assert CStoZ.ChemSymtoZ("Ga") == 31
    assert CStoZ.ChemSymtoZ("Ge") == 32
    assert CStoZ.ChemSymtoZ("As") == 33
    assert CStoZ.ChemSymtoZ("Se") == 34
    assert CStoZ.ChemSymtoZ("Br") == 35
    assert CStoZ.ChemSymtoZ("Kr") == 36
    assert CStoZ.ChemSymtoZ("Rb") == 37
    assert CStoZ.ChemSymtoZ("Sr") == 38
    assert CStoZ.ChemSymtoZ("Y") == 39
    assert CStoZ.ChemSymtoZ("Zr") == 40
    assert CStoZ.ChemSymtoZ("Nb") == 41
    assert CStoZ.ChemSymtoZ("Mo") == 42
    assert CStoZ.ChemSymtoZ("Tc") == 43
    assert CStoZ.ChemSymtoZ("Ru") == 44
    assert CStoZ.ChemSymtoZ("Rh") == 45
    assert CStoZ.ChemSymtoZ("Pd") == 46
    assert CStoZ.ChemSymtoZ("Ag") == 47
    assert CStoZ.ChemSymtoZ("Cd") == 48
    assert CStoZ.ChemSymtoZ("In") == 49
    assert CStoZ.ChemSymtoZ("Sn") == 50
    assert CStoZ.ChemSymtoZ("Sb") == 51
    assert CStoZ.ChemSymtoZ("Te") == 52
    assert CStoZ.ChemSymtoZ("I") == 53
    assert CStoZ.ChemSymtoZ("Xe") == 54
    assert CStoZ.ChemSymtoZ("Cs") == 55
    assert CStoZ.ChemSymtoZ("Ba") == 56
    assert CStoZ.ChemSymtoZ("La") == 57
    assert CStoZ.ChemSymtoZ("Ce") == 58
    assert CStoZ.ChemSymtoZ("Pr") == 59
    assert CStoZ.ChemSymtoZ("Nd") == 60
    assert CStoZ.ChemSymtoZ("Pm") == 61
    assert CStoZ.ChemSymtoZ("Sm") == 62
    assert CStoZ.ChemSymtoZ("Eu") == 63
    assert CStoZ.ChemSymtoZ("Gd") == 64
    assert CStoZ.ChemSymtoZ("Tb") == 65
    assert CStoZ.ChemSymtoZ("Dy") == 66
    assert CStoZ.ChemSymtoZ("Ho") == 67
    assert CStoZ.ChemSymtoZ("Er") == 68
    assert CStoZ.ChemSymtoZ("Tm") == 69
    assert CStoZ.ChemSymtoZ("Yb") == 70
    assert CStoZ.ChemSymtoZ("Lu") == 71
    assert CStoZ.ChemSymtoZ("Hf") == 72
    assert CStoZ.ChemSymtoZ("Ta") == 73
    assert CStoZ.ChemSymtoZ("W") == 74
    assert CStoZ.ChemSymtoZ("Re") == 75
    assert CStoZ.ChemSymtoZ("Os") == 76
    assert CStoZ.ChemSymtoZ("Ir") == 77
    assert CStoZ.ChemSymtoZ("Pt") == 78
    assert CStoZ.ChemSymtoZ("Au") == 79
    assert CStoZ.ChemSymtoZ("Hg") == 80
    assert CStoZ.ChemSymtoZ("Tl") == 81
    assert CStoZ.ChemSymtoZ("Pb") == 82
    assert CStoZ.ChemSymtoZ("Bi") == 83
    assert CStoZ.ChemSymtoZ("Po") == 84
    assert CStoZ.ChemSymtoZ("At") == 85
    assert CStoZ.ChemSymtoZ("Rn") == 86
    assert CStoZ.ChemSymtoZ("Fr") == 87
    assert CStoZ.ChemSymtoZ("Ra") == 88
    assert CStoZ.ChemSymtoZ("Ac") == 89
    assert CStoZ.ChemSymtoZ("Th") == 90
    assert CStoZ.ChemSymtoZ("Pa") == 91
    assert CStoZ.ChemSymtoZ("U") == 92
    assert CStoZ.ChemSymtoZ("Np") == 93
    assert CStoZ.ChemSymtoZ("Pu") == 94
    assert CStoZ.ChemSymtoZ("Am") == 95
    assert CStoZ.ChemSymtoZ("Cm") == 96
    assert CStoZ.ChemSymtoZ("Bk") == 97
    assert CStoZ.ChemSymtoZ("Cf") == 98
    assert CStoZ.ChemSymtoZ("Es") == 99
    assert CStoZ.ChemSymtoZ("Fm") == 100
    assert CStoZ.ChemSymtoZ("Md") == 101
    assert CStoZ.ChemSymtoZ("No") == 102
    assert CStoZ.ChemSymtoZ("Lr") == 103
    assert CStoZ.ChemSymtoZ("Rf") == 104
    assert CStoZ.ChemSymtoZ("Db") == 105
    assert CStoZ.ChemSymtoZ("Sg") == 106
    assert CStoZ.ChemSymtoZ("Bh") == 107
    assert CStoZ.ChemSymtoZ("Hs") == 108
    assert CStoZ.ChemSymtoZ("Mt") == 109
    assert CStoZ.ChemSymtoZ("Ds") == 110
    assert CStoZ.ChemSymtoZ("Rg") == 111
    assert CStoZ.ChemSymtoZ("Cn") == 112
    assert CStoZ.ChemSymtoZ("Nh") == 113
    assert CStoZ.ChemSymtoZ("Fl") == 114
    assert CStoZ.ChemSymtoZ("Mc") == 115
    assert CStoZ.ChemSymtoZ("Lv") == 116
    assert CStoZ.ChemSymtoZ("Ts") == 117
    assert CStoZ.ChemSymtoZ("Og") == 118
    assert CStoZ.ChemSymtoZ("Xx") == -1
